### ISSUE TITLE
[SOLVED] ReferenceError: crypto is not defined (octane)

### ISSUE THREAD

**Issue by ballPointPenguin** [ember-fastboot/fastboot#230]
I've built ember fastboot projects successfully with the octane blueprint recently, however today something in the dependency tree seems to be amiss.

steps to reproduce:

```
$ ember -v 
ember-cli: 3.12.0
node: 10.16.3
os: darwin x64
code/local/ember took 2s 

$ ember new fastane -b @ember/octane-app-blueprint
...
$ cd fastane
$ ember install ember-fetch
$ ember install ember-cli-fastboot
$ ember serve
```

open browser to http://localhost:4200

this message displays in the browser and console:

```


ReferenceError: crypto is not defined
    at Module.callback (/var/folders/r4/wf5lz02n6y3fhyz2btpmrjyw0000gn/T/broccoli-17631fscMVsYR8zlT/out-250-append_ember_auto_import_analyzer/assets/addon-tree-output/@ember-data/store/-private.js:3569:1)
    at Module.exports (/var/folders/r4/wf5lz02n6y3fhyz2btpmrjyw0000gn/T/broccoli-17631fscMVsYR8zlT/out-250-append_ember_auto_import_analyzer/assets/vendor/loader/loader.js:106:1)
    at Module._reify (/var/folders/r4/wf5lz02n6y3fhyz2btpmrjyw0000gn/T/broccoli-17631fscMVsYR8zlT/out-250-append_ember_auto_import_analyzer/assets/vendor/loader/loader.js:143:1)
    at Module.reify (/var/folders/r4/wf5lz02n6y3fhyz2btpmrjyw0000gn/T/broccoli-17631fscMVsYR8zlT/out-250-append_ember_auto_import_analyzer/assets/vendor/loader/loader.js:130:1)
    at Module.exports (/var/folders/r4/wf5lz02n6y3fhyz2btpmrjyw0000gn/T/broccoli-17631fscMVsYR8zlT/out-250-append_ember_auto_import_analyzer/assets/vendor/loader/loader.js:104:1)
    at Module._reify (/var/folders/r4/wf5lz02n6y3fhyz2btpmrjyw0000gn/T/broccoli-17631fscMVsYR8zlT/out-250-append_ember_auto_import_analyzer/assets/vendor/loader/loader.js:143:1)
    at Module.reify (/var/folders/r4/wf5lz02n6y3fhyz2btpmrjyw0000gn/T/broccoli-17631fscMVsYR8zlT/out-250-append_ember_auto_import_analyzer/assets/vendor/loader/loader.js:130:1)
    at Module.exports (/var/folders/r4/wf5lz02n6y3fhyz2btpmrjyw0000gn/T/broccoli-17631fscMVsYR8zlT/out-250-append_ember_auto_import_analyzer/assets/vendor/loader/loader.js:104:1)
    at Module._reify (/var/folders/r4/wf5lz02n6y3fhyz2btpmrjyw0000gn/T/broccoli-17631fscMVsYR8zlT/out-250-append_ember_auto_import_analyzer/assets/vendor/loader/loader.js:143:1)
    at Module.reify (/var/folders/r4/wf5lz02n6y3fhyz2btpmrjyw0000gn/T/broccoli-17631fscMVsYR8zlT/out-250-append_ember_auto_import_analyzer/assets/vendor/loader/loader.js:130:1)
    at Module.exports (/var/folders/r4/wf5lz02n6y3fhyz2btpmrjyw0000gn/T/broccoli-17631fscMVsYR8zlT/out-250-append_ember_auto_import_analyzer/assets/vendor/loader/loader.js:104:1)
    at requireModule (/var/folders/r4/wf5lz02n6y3fhyz2btpmrjyw0000gn/T/broccoli-17631fscMVsYR8zlT/out-250-append_ember_auto_import_analyzer/assets/vendor/loader/loader.js:27:1)
    at r (/var/folders/r4/wf5lz02n6y3fhyz2btpmrjyw0000gn/T/broccoli-17631fscMVsYR8zlT/out-250-append_ember_auto_import_analyzer/assets/vendor/loader/loader.js:176:1)
    at resolveInitializer (/var/folders/r4/wf5lz02n6y3fhyz2btpmrjyw0000gn/T/broccoli-17631fscMVsYR8zlT/out-250-append_ember_auto_import_analyzer/assets/addon-tree-output/ember-load-initializers/index.js:10:1)
    at registerInitializers (/var/folders/r4/wf5lz02n6y3fhyz2btpmrjyw0000gn/T/broccoli-17631fscMVsYR8zlT/out-250-append_ember_auto_import_analyzer/assets/addon-tree-output/ember-load-initializers/index.js:27:1)
    at loadInitializers (/var/folders/r4/wf5lz02n6y3fhyz2btpmrjyw0000gn/T/broccoli-17631fscMVsYR8zlT/out-250-append_ember_auto_import_analyzer/assets/addon-tree-output/ember-load-initializers/index.js:68:1)
    at Module.callback (/var/folders/r4/wf5lz02n6y3fhyz2btpmrjyw0000gn/T/broccoli-17631fscMVsYR8zlT/out-250-append_ember_auto_import_analyzer/assets/fastane/app.js:20:1)
    at Module.exports (/var/folders/r4/wf5lz02n6y3fhyz2btpmrjyw0000gn/T/broccoli-17631fscMVsYR8zlT/out-250-append_ember_auto_import_analyzer/assets/vendor/loader/loader.js:106:1)
    at Module._reify (/var/folders/r4/wf5lz02n6y3fhyz2btpmrjyw0000gn/T/broccoli-17631fscMVsYR8zlT/out-250-append_ember_auto_import_analyzer/assets/vendor/loader/loader.js:143:1)
    at Module.reify (/var/folders/r4/wf5lz02n6y3fhyz2btpmrjyw0000gn/T/broccoli-17631fscMVsYR8zlT/out-250-append_ember_auto_import_analyzer/assets/vendor/loader/loader.js:130:1)
    at Module.exports (/var/folders/r4/wf5lz02n6y3fhyz2btpmrjyw0000gn/T/broccoli-17631fscMVsYR8zlT/out-250-append_ember_auto_import_analyzer/assets/vendor/loader/loader.js:104:1)
    at Object.requireModule (/var/folders/r4/wf5lz02n6y3fhyz2btpmrjyw0000gn/T/broccoli-17631fscMVsYR8zlT/out-250-append_ember_auto_import_analyzer/assets/vendor/loader/loader.js:27:1)
    at Object.<anonymous> (/Users/brosas/code/local/ember/fastane/node_modules/fastboot/src/ember-app.js:213:18)
    at VMSandbox.run (/Users/brosas/code/local/ember/fastane/node_modules/fastboot/src/vm-sandbox.js:18:15)
    at EmberApp.createEmberApp (/Users/brosas/code/local/ember/fastane/node_modules/fastboot/src/ember-app.js:212:30)
    at EmberApp.retrieveSandboxedApp (/Users/brosas/code/local/ember/fastane/node_modules/fastboot/src/ember-app.js:237:17)
    at new EmberApp (/Users/brosas/code/local/ember/fastane/node_modules/fastboot/src/ember-app.js:61:21)
    at FastBoot._buildEmberApp (/Users/brosas/code/local/ember/fastane/node_modules/fastboot/src/index.js:114:17)
    at new FastBoot (/Users/brosas/code/local/ember/fastane/node_modules/fastboot/src/index.js:52:10)
    at app.use (/Users/brosas/code/local/ember/fastane/node_modules/ember-cli-fastboot/index.js:330:29)
    at Layer.handle [as handle_request] (/Users/brosas/code/local/ember/fastane/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/brosas/code/local/ember/fastane/node_modules/express/lib/router/index.js:317:13)
    at /Users/brosas/code/local/ember/fastane/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/brosas/code/local/ember/fastane/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/brosas/code/local/ember/fastane/node_modules/express/lib/router/index.js:275:10)
    at err (/Users/brosas/code/local/ember/fastane/node_modules/ember-cli/lib/tasks/server/middleware/broccoli-watcher/index.js:54:11)
    at watcher.then (/Users/brosas/code/local/ember/fastane/node_modules/broccoli-middleware/lib/watcher-middleware.js:35:7)
    at tryCatcher (/Users/brosas/code/local/ember/fastane/node_modules/ember-cli/node_modules/rsvp/dist/lib/rsvp/-internal.js:39:19)
    at invokeCallback (/Users/brosas/code/local/ember/fastane/node_modules/ember-cli/node_modules/rsvp/dist/lib/rsvp/-internal.js:211:31)
    at /Users/brosas/code/local/ember/fastane/node_modules/ember-cli/node_modules/rsvp/dist/lib/rsvp/then.js:26:14
    at flush (/Users/brosas/code/local/ember/fastane/node_modules/ember-cli/node_modules/rsvp/dist/lib/rsvp/asap.js:80:5)
    at process._tickCallback (internal/process/next_tick.js:61:11)
```

**Comment by ballPointPenguin** [comment]
This seems to be a replica of https://github.com/emberjs/data/issues/6458

**Comment by ballPointPenguin** [comment]
This is solved by applying the commit from https://github.com/emberjs/data/pull/6330

**Comment by ballPointPenguin** [comment]
better solution (for now):

```
npm i -D ember-data@v.3.12.2
```
