### ISSUE TITLE
`TypeError: FastBoot.config is not a function` on initial app load

### ISSUE THREAD

**Issue by gabrielgrant** [ember-fastboot/fastboot#72]
I believe I've followed the README's usage instructions

<details>
<summary>

Setup procedure</summary>

```
$ cd <app-dir>
$ ember install ember-cli-fastboot
$ # ... add dependencies to fastbootDependencies
$ ember build --environment production
$ cd ../new-dir
$ npm install fastboot
```

</details>

but I'm getting and error when I try to initialize the app:
`TypeError: FastBoot.config is not a function`

<details>
<summary>

Full traceback</summary>

```
$ node --harmony
> const FastBoot = require('fastboot');
undefined
> let app = new FastBoot({distPath: '../appdir/dist'});
TypeError: FastBoot.config is not a function
    at r.callback (/path/to/appdir/dist/fastboot/chexec-4b43a9d50d6c4ddb7a7238f13ffeb126.js:3:11339)
    at r.exports (/path/to/appdir/dist/fastboot/vendor-a977a12b034745a0caa0ac14c4319f53.js:1:1991)
    at r.build (/path/to/appdir/dist/fastboot/vendor-a977a12b034745a0caa0ac14c4319f53.js:1:2753)
    at a (/path/to/appdir/dist/fastboot/vendor-a977a12b034745a0caa0ac14c4319f53.js:1:926)
    at r.reify (/path/to/appdir/dist/fastboot/vendor-a977a12b034745a0caa0ac14c4319f53.js:1:2466)
    at r.build (/path/to/appdir/dist/fastboot/vendor-a977a12b034745a0caa0ac14c4319f53.js:1:2740)
    at a (/path/to/appdir/dist/fastboot/vendor-a977a12b034745a0caa0ac14c4319f53.js:1:926)
    at r.reify (/path/to/appdir/dist/fastboot/vendor-a977a12b034745a0caa0ac14c4319f53.js:1:2466)
    at r.build (/path/to/appdir/dist/fastboot/vendor-a977a12b034745a0caa0ac14c4319f53.js:1:2740)
    at a (/path/to/appdir/dist/fastboot/vendor-a977a12b034745a0caa0ac14c4319f53.js:1:926)
    at Object.requireModule (/path/to/appdir/dist/fastboot/vendor-a977a12b034745a0caa0ac14c4319f53.js:1:3030)
    at Object.<anonymous> (/path/to/appdir-cli/node_modules/fastboot/lib/ember-app.js:129:18)
    at Sandbox.VMSandbox.run (/path/to/appdir-cli/node_modules/fastboot/lib/vm-sandbox.js:18:13)
    at EmberApp.retrieveSandboxedApp (/path/to/appdir-cli/node_modules/fastboot/lib/ember-app.js:128:30)
    at new EmberApp (/path/to/appdir-cli/node_modules/fastboot/lib/ember-app.js:41:21)
    at FastBoot._buildEmberApp (/path/to/appdir-cli/node_modules/fastboot/index.js:101:17)
    at new FastBoot (/path/to/appdir-cli/node_modules/fastboot/index.js:47:10)
    at repl:1:-51
    at sigintHandlersWrap (vm.js:32:31)
    at sigintHandlersWrap (vm.js:96:12)
    at ContextifyScript.Script.runInContext (vm.js:31:12)
    at REPLServer.defaultEval (repl.js:308:29)
    at bound (domain.js:280:14)
    at REPLServer.runBound [as eval] (domain.js:293:12)
    at REPLServer.<anonymous> (repl.js:489:10)
    at emitOne (events.js:101:20)
    at REPLServer.emit (events.js:188:7)
    at REPLServer.Interface._onLine (readline.js:232:10)
    at REPLServer.Interface._line (readline.js:574:8)
    at REPLServer.Interface._ttyWrite (readline.js:851:14)
    at ReadStream.onkeypress (readline.js:119:10)
    at emitTwo (events.js:106:13)
    at ReadStream.emit (events.js:191:7)
    at emitKeys (internal/readline.js:385:14)
    at next (native)
    at ReadStream.onData (readline.js:947:36)
    at emitOne (events.js:96:13)
    at ReadStream.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:177:18)
    at ReadStream.Readable.push (_stream_readable.js:135:10)
    at TTY.onread (net.js:542:20)
```

</details>

I'm likely doing something silly, but strangely, grepping for `Fastboot.config` deosn't seem to turn up anything so it's not clear how I should go about debugging this...

**Comment by aesopwolf** [comment]
I just ran into the same issue after updating from ember-cli-fastboot 0.6.2 to 1.0.0-beta.4.

**Comment by jasonmit** [comment]
If anyone can push an example app that is encountering this to git, I'd love to help get to the bottom of it.

**Comment by danmcclain** [comment]
Are you using the latest versions of both ember-cli-fastboot and fastboot? If you are using an older version of fastboot with a newer version of ember-cli-fastboot, the config won't be exported

**Comment by aesopwolf** [comment]
thanks @danmcclain, that was definitely the issue

**Comment by danmcclain** [comment]
Seemed to be cause by ember-cli-fastboot and fastboot version mismatch, please comment if you see the issue again
